### ISSUE TITLE
add dumped output

### ISSUE THREAD

**Issue by nuxodin** [WebReflection/is-it-worker#1]
I have seen your new script.
It occurred to me that this is a good use-case for my dump.js script.

I forked your repo and implemented dump.js.
Here's what it looks like (doesn't work in firefox!):
http://raw.githack.com/nuxodin/is-it-worker/main/index.html?self

I'm sure you'll see how this works in my code in a moment.
https://github.com/nuxodin/is-it-worker/blob/main/worker.js

Unfortunately worker-module didn't work in firefox yet, so you have to test it in chrome.

Just as a suggestion.

Tell me if you want me to do a PR, or if this is not your use-case and I'm just spamming you.

**Comment by WebReflection** [comment]
I'm happy to keep this as simple as possible and point at your link in the README explaining it doesn't work in Firefox (yet?) and that it shows more around references ... would that work for you?

**Comment by WebReflection** [comment]
Actually ... I think the list of keys if the thing is an object is very helpfull ... and that doesn't need any special requirement ... I'll improve this inspired by your demo, but it has to work everywhere or it loses its purpose, I hope you understand that.

**Comment by nuxodin** [comment]
Yes, it makes me happy when it can serve as inspiration.
It would be cool to navigate through objects by clicking on the property
Firefox is about to allow workers soon, but it's true, it doesn't make sense if it doesn't cover current browsers.

**Comment by WebReflection** [comment]
it's up and running (just showing keys per namespace/object/function/constructor)
